### ISSUE TITLE
Repair Tower Script and initial set up

### ISSUE THREAD

**Issue by sgh725** [devilcry3/AR-TowerDefense_GIMM110#17]

**Comment by sgh725** [comment]
Repair Tower script: Sets health to max health for all objects with tag "Tower."
I have added the method RestoreAllHealth to end of Health script.
For testing purposes: Activate Repair Tower by pressing R. Can comment out line 29 in Health script to test this more easily. (That line sets currentHealth to maxHealth in start.)

**Comment by devilcry3** [comment]
Currently Working on getting files to push properly to gethub, running into errors preventing push.

**Comment by sgh725** [comment]
Pushed to repository.

Repair Tower script: Sets health to max health for all objects with tag "Tower."
I have added the method RestoreAllHealth to end of Health script.
For testing purposes: Activate Repair Tower by pressing R. Can comment out line 29 in Health script to test this more easily. (That line sets currentHealth to maxHealth in start.)
