### ISSUE TITLE
Ballista Tower Script and initial set up

### ISSUE THREAD

**Issue by sgh725** [devilcry3/AR-TowerDefense_GIMM110#18]

**Comment by sgh725** [comment]
Ballista Tower with placeholder sprites. Fires spear in a straight line at angle fireAngle.

**Comment by devilcry3** [comment]
Currently Working on getting files to push properly to gethub, running into errors preventing push.

**Comment by sgh725** [comment]
Pushed to Github. Ballista tower with placeholder sprites. Fires spear in a straight lie at angle fireAngle.
